FROM golang:1.23.2-alpine AS builder-go

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY src/ ./src/

RUN go build ./src/main.go



FROM node:current-alpine AS builder-npm

WORKDIR /web

COPY public/ ./

RUN npm install

RUN npm run build



FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder-go /app/main .

COPY --from=builder-npm /web/dist ./public

EXPOSE 80

CMD ["./main", "prod"]
