# Showmaster Docker Compose file

services:
  app:
    image: braunelias/showmaster:latest
    ports:
      - "8080:3000"
    depends_on:
      - psql
      - redis
    environment:
      - PSQL_HOST=psql
      - PSQL_PORT=5432
      - PSQL_USER=showmaster
      - PSQL_PASSWORD=showmaster
      - PSQL_DB=showmaster
      - PSQL_TIMEZONE=Europe/Berlin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=showmaster
      - REDIS_DB=0
    networks:
      - showmaster_network
    healthcheck:
      test: wget --quit --tries=1 --spider http://127.0.0.1:3000/healthcheck || exit 1
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 30s

  psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: showmaster
      POSTGRES_PASSWORD: showmaster
      POSTGRES_DB: showmaster
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - showmaster_network

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=showmaster
    networks:
      - showmaster_network

volumes:
  psql_data:

networks:
  showmaster_network:
    external: false